[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stable_swap_circuit_breaker = "STABL circu1tBreaKerProgram1111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
